// -*- Mode: Go; indent-tabs-mode: t -*-
//
// Copyright (C) 2022 Intel Corporation
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by gen_commands.py DO NOT EDIT.

package search

type EndSearchFunction struct{}

func (_ *EndSearchFunction) Request() interface{} {
	return &EndSearch{}
}
func (_ *EndSearchFunction) Response() interface{} {
	return &EndSearchResponse{}
}

type FindEventsFunction struct{}

func (_ *FindEventsFunction) Request() interface{} {
	return &FindEvents{}
}
func (_ *FindEventsFunction) Response() interface{} {
	return &FindEventsResponse{}
}

type FindMetadataFunction struct{}

func (_ *FindMetadataFunction) Request() interface{} {
	return &FindMetadata{}
}
func (_ *FindMetadataFunction) Response() interface{} {
	return &FindMetadataResponse{}
}

type FindRecordingsFunction struct{}

func (_ *FindRecordingsFunction) Request() interface{} {
	return &FindRecordings{}
}
func (_ *FindRecordingsFunction) Response() interface{} {
	return &FindRecordingsResponse{}
}

type GetEventSearchResultsFunction struct{}

func (_ *GetEventSearchResultsFunction) Request() interface{} {
	return &GetEventSearchResults{}
}
func (_ *GetEventSearchResultsFunction) Response() interface{} {
	return &GetEventSearchResultsResponse{}
}

type GetMetadataSearchResultsFunction struct{}

func (_ *GetMetadataSearchResultsFunction) Request() interface{} {
	return &GetMetadataSearchResults{}
}
func (_ *GetMetadataSearchResultsFunction) Response() interface{} {
	return &GetMetadataSearchResultsResponse{}
}

type GetRecordingInformationFunction struct{}

func (_ *GetRecordingInformationFunction) Request() interface{} {
	return &GetRecordingInformation{}
}
func (_ *GetRecordingInformationFunction) Response() interface{} {
	return &GetRecordingInformationResponse{}
}

type GetRecordingSearchResultsFunction struct{}

func (_ *GetRecordingSearchResultsFunction) Request() interface{} {
	return &GetRecordingSearchResults{}
}
func (_ *GetRecordingSearchResultsFunction) Response() interface{} {
	return &GetRecordingSearchResultsResponse{}
}

type GetServiceCapabilitiesFunction struct{}

func (_ *GetServiceCapabilitiesFunction) Request() interface{} {
	return &GetServiceCapabilities{}
}
func (_ *GetServiceCapabilitiesFunction) Response() interface{} {
	return &GetServiceCapabilitiesResponse{}
}
