// -*- Mode: Go; indent-tabs-mode: t -*-
//
// Copyright (C) 2022 Intel Corporation
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by gen_commands.py DO NOT EDIT.

package receiver

type ConfigureReceiverFunction struct{}

func (_ *ConfigureReceiverFunction) Request() interface{} {
	return &ConfigureReceiver{}
}
func (_ *ConfigureReceiverFunction) Response() interface{} {
	return &ConfigureReceiverResponse{}
}

type CreatePullPointFunction struct{}

func (_ *CreatePullPointFunction) Request() interface{} {
	return &CreatePullPoint{}
}
func (_ *CreatePullPointFunction) Response() interface{} {
	return &CreatePullPointResponse{}
}

type CreateReceiverFunction struct{}

func (_ *CreateReceiverFunction) Request() interface{} {
	return &CreateReceiver{}
}
func (_ *CreateReceiverFunction) Response() interface{} {
	return &CreateReceiverResponse{}
}

type DeleteReceiverFunction struct{}

func (_ *DeleteReceiverFunction) Request() interface{} {
	return &DeleteReceiver{}
}
func (_ *DeleteReceiverFunction) Response() interface{} {
	return &DeleteReceiverResponse{}
}

type DestroyPullPointFunction struct{}

func (_ *DestroyPullPointFunction) Request() interface{} {
	return &DestroyPullPoint{}
}
func (_ *DestroyPullPointFunction) Response() interface{} {
	return &DestroyPullPointResponse{}
}

type GetCurrentMessageFunction struct{}

func (_ *GetCurrentMessageFunction) Request() interface{} {
	return &GetCurrentMessage{}
}
func (_ *GetCurrentMessageFunction) Response() interface{} {
	return &GetCurrentMessageResponse{}
}

type GetMessagesFunction struct{}

func (_ *GetMessagesFunction) Request() interface{} {
	return &GetMessages{}
}
func (_ *GetMessagesFunction) Response() interface{} {
	return &GetMessagesResponse{}
}

type GetReceiverFunction struct{}

func (_ *GetReceiverFunction) Request() interface{} {
	return &GetReceiver{}
}
func (_ *GetReceiverFunction) Response() interface{} {
	return &GetReceiverResponse{}
}

type GetReceiverStateFunction struct{}

func (_ *GetReceiverStateFunction) Request() interface{} {
	return &GetReceiverState{}
}
func (_ *GetReceiverStateFunction) Response() interface{} {
	return &GetReceiverStateResponse{}
}

type GetReceiversFunction struct{}

func (_ *GetReceiversFunction) Request() interface{} {
	return &GetReceivers{}
}
func (_ *GetReceiversFunction) Response() interface{} {
	return &GetReceiversResponse{}
}

type GetServiceCapabilitiesFunction struct{}

func (_ *GetServiceCapabilitiesFunction) Request() interface{} {
	return &GetServiceCapabilities{}
}
func (_ *GetServiceCapabilitiesFunction) Response() interface{} {
	return &GetServiceCapabilitiesResponse{}
}

type PauseSubscriptionFunction struct{}

func (_ *PauseSubscriptionFunction) Request() interface{} {
	return &PauseSubscription{}
}
func (_ *PauseSubscriptionFunction) Response() interface{} {
	return &PauseSubscriptionResponse{}
}

type RenewFunction struct{}

func (_ *RenewFunction) Request() interface{} {
	return &Renew{}
}
func (_ *RenewFunction) Response() interface{} {
	return &RenewResponse{}
}

type ResumeSubscriptionFunction struct{}

func (_ *ResumeSubscriptionFunction) Request() interface{} {
	return &ResumeSubscription{}
}
func (_ *ResumeSubscriptionFunction) Response() interface{} {
	return &ResumeSubscriptionResponse{}
}

type SetReceiverModeFunction struct{}

func (_ *SetReceiverModeFunction) Request() interface{} {
	return &SetReceiverMode{}
}
func (_ *SetReceiverModeFunction) Response() interface{} {
	return &SetReceiverModeResponse{}
}

type SubscribeFunction struct{}

func (_ *SubscribeFunction) Request() interface{} {
	return &Subscribe{}
}
func (_ *SubscribeFunction) Response() interface{} {
	return &SubscribeResponse{}
}

type UnsubscribeFunction struct{}

func (_ *UnsubscribeFunction) Request() interface{} {
	return &Unsubscribe{}
}
func (_ *UnsubscribeFunction) Response() interface{} {
	return &UnsubscribeResponse{}
}
