// -*- Mode: Go; indent-tabs-mode: t -*-
//
// Copyright (C) 2022 Intel Corporation
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by gen_commands.py DO NOT EDIT.

package replay

type GetReplayConfigurationFunction struct{}

func (_ *GetReplayConfigurationFunction) Request() interface{} {
	return &GetReplayConfiguration{}
}
func (_ *GetReplayConfigurationFunction) Response() interface{} {
	return &GetReplayConfigurationResponse{}
}

type GetReplayUriFunction struct{}

func (_ *GetReplayUriFunction) Request() interface{} {
	return &GetReplayUri{}
}
func (_ *GetReplayUriFunction) Response() interface{} {
	return &GetReplayUriResponse{}
}

type GetServiceCapabilitiesFunction struct{}

func (_ *GetServiceCapabilitiesFunction) Request() interface{} {
	return &GetServiceCapabilities{}
}
func (_ *GetServiceCapabilitiesFunction) Response() interface{} {
	return &GetServiceCapabilitiesResponse{}
}

type SetReplayConfigurationFunction struct{}

func (_ *SetReplayConfigurationFunction) Request() interface{} {
	return &SetReplayConfiguration{}
}
func (_ *SetReplayConfigurationFunction) Response() interface{} {
	return &SetReplayConfigurationResponse{}
}
